project:
  type: website

website:
  title: "Visual Analytics Project - Hotel Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual