project:
  type: website

website:
  title: "Visual Analytics Project - HotelViz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://hotel-viz.shinyapps.io/hotel_viz/
        text: Shiny App
      - href: proposal.qmd
        text: Overview
      - href: user_guide.qmd
        text: User Guide
theme: flatly
toc: true
format: revealjs
css: styles.css