project:
  type: website

website:
  title: "Visual Analytics Project - Hotel Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - text: User Guide
      - text: Shiny App
      - href: about.qmd
        text: About Us

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual