project:
  type: website

website:
  title: "Visual Analytics Project - Hotel Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Overview
      - href: user_guide.qmd
        text: User Guide
      - href: https://hotel-viz.shinyapps.io/hotel_viz/
        text: Shiny App
      - href: about.qmd
        text: About Us

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual