

pacman::p_load(shiny, shinythemes, tidyverse, rpart,rpart.plot, shinyWidgets)

hotel_data <- read.csv('hotel_viz/data/hotel.csv')

index <- sample(1:601, size = trunc(.8 * 601))
train_df <- hotel_data %>%
  filter(row_number() %in% index)

test_df <- hotel_data %>%
  filter(!(row_number() %in% index))

var_list <- colnames(hotel_data)[3:33]


var_list_default <- var_list

var_list


makeTree = function(train_df, model_vars, min_split, min_bucket, max_depth) {
  # Takes a list of model variables (strings), a minimum split parameter
  # (int), a minimum bucket size parameter (int), and a maximum tree depth
  # parameter (int) as inputs and then returns an rpart classification tree
  # created with those parameters using Gini-indexes without any pruning.
  
  train_dat = train_df
  # create an rpart compatible formula for the model from the chosen vars
  f = paste("IsCanceled ~ ", paste(model_vars, collapse = " + "))
  
  # rpart is performs the split calculations and returns the tree
  tree = rpart(
    as.formula(f),
    method = "class",  # sets it up as a classification problem
    data = train_dat,
    parms = list(split = "gini"),  # ensures rpart uses gini indexes
    minsplit = min_split,
    minbucket = min_bucket,
    maxdepth = max_depth,
    cp = 0  # complexity parameter, at zero prevents pruning on branches
  )
  
  return(tree)
}

useTree = function(tree, test_df) {
  # Takes a tree generated by rpart and a filename (string) as input and
  # then predicts the labels of the data in that file using the tree. It
  # returns a dataframe with two bool (0,1) columns: prediction and truth.
  
  data = test_df
  prediction = predict(tree, data, type = "class")
  results = as.data.frame(prediction)
  results$truth = data$IsCanceled
  
  return(results)
}

makeTree(train_df, model_vars=var_list,3,4,5)



cor(train_df)


colnames(train_df)[3:33]


tree <- eventReactive(input$create_tree, {
  
  # Subset the data to the selected predictors
  my_data_subset <- my_data[, input$predictors]
  
  # Remove highly correlated predictors
  cleaned_data <- removeCorrelatedPredictors(my_data_subset, threshold = 0.7)
  
  # Train the decision tree using rpart
  rpart_model <- rpart(IsCanceled ~ ., data = cleaned_data, method = "class",
                       parms = list(split = "gini"), minsplit = input$min_split,
                       minbucket = input$min_bucket, maxdepth = input$max_depth, cp = 0)
  
  return(rpart_model)
  
})